# GCPIP should be set as environment variable
dookug:
    write:
        document: true
    service:
        document:
            base:
                uri: http://${gcpIp}:8082
            management:
                uri: http://${gcpIp}:9992
    client:
        document/mp-rest/url: http://${gcpIp}:8082
